# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/plutopropassessctrl.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProprioceptionAssessWindow(object):
    def setupUi(self, ProprioceptionAssessWindow):
        ProprioceptionAssessWindow.setObjectName("ProprioceptionAssessWindow")
        ProprioceptionAssessWindow.resize(751, 429)
        ProprioceptionAssessWindow.setMinimumSize(QtCore.QSize(751, 429))
        ProprioceptionAssessWindow.setMaximumSize(QtCore.QSize(751, 429))
        self.centralwidget = QtWidgets.QWidget(ProprioceptionAssessWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 731, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.hocGraph = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.hocGraph.setObjectName("hocGraph")
        self.verticalLayout.addWidget(self.hocGraph)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbStartStopProtocl = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.pbStartStopProtocl.setFont(font)
        self.pbStartStopProtocl.setObjectName("pbStartStopProtocl")
        self.horizontalLayout_2.addWidget(self.pbStartStopProtocl)
        self.checkBoxPauseProtocol = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.checkBoxPauseProtocol.setFont(font)
        self.checkBoxPauseProtocol.setObjectName("checkBoxPauseProtocol")
        self.horizontalLayout_2.addWidget(self.checkBoxPauseProtocol)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textInstruction = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textInstruction.setEnabled(False)
        self.textInstruction.setMinimumSize(QtCore.QSize(729, 71))
        self.textInstruction.setMaximumSize(QtCore.QSize(729, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.textInstruction.setFont(font)
        self.textInstruction.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(240, 240, 240);")
        self.textInstruction.setObjectName("textInstruction")
        self.verticalLayout.addWidget(self.textInstruction)
        ProprioceptionAssessWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ProprioceptionAssessWindow)
        self.statusbar.setObjectName("statusbar")
        ProprioceptionAssessWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProprioceptionAssessWindow)
        QtCore.QMetaObject.connectSlotsByName(ProprioceptionAssessWindow)

    def retranslateUi(self, ProprioceptionAssessWindow):
        _translate = QtCore.QCoreApplication.translate
        ProprioceptionAssessWindow.setWindowTitle(_translate("ProprioceptionAssessWindow", "PLUTO Proprioception Assessment Control Window"))
        self.label.setText(_translate("ProprioceptionAssessWindow", "PLUTO Proprioception Assessment"))
        self.pbStartStopProtocl.setText(_translate("ProprioceptionAssessWindow", "Start Protocol"))
        self.checkBoxPauseProtocol.setText(_translate("ProprioceptionAssessWindow", "Pause Protocol"))
        self.label_2.setText(_translate("ProprioceptionAssessWindow", "TextLabel"))
