# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/plutoposholdassess.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PosHoldAssessWindow(object):
    def setupUi(self, PosHoldAssessWindow):
        PosHoldAssessWindow.setObjectName("PosHoldAssessWindow")
        PosHoldAssessWindow.resize(522, 451)
        PosHoldAssessWindow.setMinimumSize(QtCore.QSize(522, 451))
        PosHoldAssessWindow.setMaximumSize(QtCore.QSize(522, 451))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        PosHoldAssessWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(PosHoldAssessWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(12)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: rgb(170, 0, 0);")
        self.lblTitle.setObjectName("lblTitle")
        self.horizontalLayout.addWidget(self.lblTitle)
        self.cbTrialRun = QtWidgets.QCheckBox(self.centralwidget)
        self.cbTrialRun.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(10)
        self.cbTrialRun.setFont(font)
        self.cbTrialRun.setStyleSheet("color: rgb(170, 0, 0);")
        self.cbTrialRun.setObjectName("cbTrialRun")
        self.horizontalLayout.addWidget(self.cbTrialRun)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hocGraph = QtWidgets.QGraphicsView(self.centralwidget)
        self.hocGraph.setMaximumSize(QtCore.QSize(500, 375))
        self.hocGraph.setObjectName("hocGraph")
        self.verticalLayout.addWidget(self.hocGraph)
        self.lblStatus = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(10)
        self.lblStatus.setFont(font)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        PosHoldAssessWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PosHoldAssessWindow)
        QtCore.QMetaObject.connectSlotsByName(PosHoldAssessWindow)

    def retranslateUi(self, PosHoldAssessWindow):
        _translate = QtCore.QCoreApplication.translate
        PosHoldAssessWindow.setWindowTitle(_translate("PosHoldAssessWindow", "Position Hold Assessment"))
        self.lblTitle.setText(_translate("PosHoldAssessWindow", "PLUTO ROM Assessment"))
        self.cbTrialRun.setText(_translate("PosHoldAssessWindow", "Trial Run"))
        self.lblStatus.setText(_translate("PosHoldAssessWindow", "TextLabel"))
