# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/plutotestcontrol.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlutoTestControlWindow(object):
    def setupUi(self, PlutoTestControlWindow):
        PlutoTestControlWindow.setObjectName("PlutoTestControlWindow")
        PlutoTestControlWindow.resize(395, 171)
        PlutoTestControlWindow.setMinimumSize(QtCore.QSize(395, 171))
        PlutoTestControlWindow.setMaximumSize(QtCore.QSize(395, 171))
        self.centralwidget = QtWidgets.QWidget(PlutoTestControlWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbControlType = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.gbControlType.setFont(font)
        self.gbControlType.setObjectName("gbControlType")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gbControlType)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 347, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioNone = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioNone.setObjectName("radioNone")
        self.horizontalLayout.addWidget(self.radioNone)
        self.radioTorque = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioTorque.setObjectName("radioTorque")
        self.horizontalLayout.addWidget(self.radioTorque)
        self.radioPosition = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioPosition.setObjectName("radioPosition")
        self.horizontalLayout.addWidget(self.radioPosition)
        self.verticalLayout.addWidget(self.gbControlType)
        self.lblTargetValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.lblTargetValue.setFont(font)
        self.lblTargetValue.setStyleSheet("color: rgb(170, 0, 0);")
        self.lblTargetValue.setObjectName("lblTargetValue")
        self.verticalLayout.addWidget(self.lblTargetValue)
        self.hSliderTgtValue = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.hSliderTgtValue.setMaximum(1000)
        self.hSliderTgtValue.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderTgtValue.setObjectName("hSliderTgtValue")
        self.verticalLayout.addWidget(self.hSliderTgtValue)
        PlutoTestControlWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PlutoTestControlWindow)
        QtCore.QMetaObject.connectSlotsByName(PlutoTestControlWindow)

    def retranslateUi(self, PlutoTestControlWindow):
        _translate = QtCore.QCoreApplication.translate
        PlutoTestControlWindow.setWindowTitle(_translate("PlutoTestControlWindow", "PLUTO Test Window"))
        self.gbControlType.setTitle(_translate("PlutoTestControlWindow", "Choose Control Type"))
        self.radioNone.setText(_translate("PlutoTestControlWindow", "No Control"))
        self.radioTorque.setText(_translate("PlutoTestControlWindow", "Torque"))
        self.radioPosition.setText(_translate("PlutoTestControlWindow", "Position"))
        self.lblTargetValue.setText(_translate("PlutoTestControlWindow", "Target Value:"))
