# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/plutodataview.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DevDataWindow(object):
    def setupUi(self, DevDataWindow):
        DevDataWindow.setObjectName("DevDataWindow")
        DevDataWindow.setEnabled(False)
        DevDataWindow.resize(431, 329)
        DevDataWindow.setMinimumSize(QtCore.QSize(431, 329))
        DevDataWindow.setMaximumSize(QtCore.QSize(431, 329))
        self.centralwidget = QtWidgets.QWidget(DevDataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textDevData = QtWidgets.QTextEdit(self.centralwidget)
        self.textDevData.setEnabled(False)
        self.textDevData.setGeometry(QtCore.QRect(10, 10, 411, 311))
        font = QtGui.QFont()
        font.setFamily("Space Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textDevData.setFont(font)
        self.textDevData.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 10pt \"Space Mono\";\n"
"color: rgb(0, 255, 60);")
        self.textDevData.setMarkdown("")
        self.textDevData.setObjectName("textDevData")
        DevDataWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DevDataWindow)
        QtCore.QMetaObject.connectSlotsByName(DevDataWindow)

    def retranslateUi(self, DevDataWindow):
        _translate = QtCore.QCoreApplication.translate
        DevDataWindow.setWindowTitle(_translate("DevDataWindow", "PLUTO Data Window"))
        self.textDevData.setHtml(_translate("DevDataWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Space Mono\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
