# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/plutopropvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssessmentVisualizer(object):
    def setupUi(self, AssessmentVisualizer):
        AssessmentVisualizer.setObjectName("AssessmentVisualizer")
        AssessmentVisualizer.resize(751, 323)
        AssessmentVisualizer.setMinimumSize(QtCore.QSize(751, 323))
        AssessmentVisualizer.setMaximumSize(QtCore.QSize(751, 323))
        self.centralwidget = QtWidgets.QWidget(AssessmentVisualizer)
        self.centralwidget.setObjectName("centralwidget")
        self.hocGraph = QtWidgets.QGraphicsView(self.centralwidget)
        self.hocGraph.setGeometry(QtCore.QRect(10, 10, 731, 231))
        self.hocGraph.setObjectName("hocGraph")
        AssessmentVisualizer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AssessmentVisualizer)
        self.statusbar.setObjectName("statusbar")
        AssessmentVisualizer.setStatusBar(self.statusbar)

        self.retranslateUi(AssessmentVisualizer)
        QtCore.QMetaObject.connectSlotsByName(AssessmentVisualizer)

    def retranslateUi(self, AssessmentVisualizer):
        _translate = QtCore.QCoreApplication.translate
        AssessmentVisualizer.setWindowTitle(_translate("AssessmentVisualizer", "MainWindow"))
