# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/plutopropvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PropriceptionAssessmentWindow(object):
    def setupUi(self, PropriceptionAssessmentWindow):
        PropriceptionAssessmentWindow.setObjectName("PropriceptionAssessmentWindow")
        PropriceptionAssessmentWindow.setWindowModality(QtCore.Qt.NonModal)
        PropriceptionAssessmentWindow.resize(820, 417)
        PropriceptionAssessmentWindow.setMinimumSize(QtCore.QSize(820, 417))
        PropriceptionAssessmentWindow.setMaximumSize(QtCore.QSize(820, 417))
        self.centralwidget = QtWidgets.QWidget(PropriceptionAssessmentWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 801, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hocGraph = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.hocGraph.setObjectName("hocGraph")
        self.verticalLayout.addWidget(self.hocGraph)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pdStartStopProtocol = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.pdStartStopProtocol.setFont(font)
        self.pdStartStopProtocol.setObjectName("pdStartStopProtocol")
        self.horizontalLayout_3.addWidget(self.pdStartStopProtocol)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.checkBoxPauseProtocol = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.checkBoxPauseProtocol.setFont(font)
        self.checkBoxPauseProtocol.setObjectName("checkBoxPauseProtocol")
        self.horizontalLayout_3.addWidget(self.checkBoxPauseProtocol)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.lblInformation = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.lblInformation.setFont(font)
        self.lblInformation.setObjectName("lblInformation")
        self.verticalLayout.addWidget(self.lblInformation)
        self.textDetails = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textDetails.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textDetails.setObjectName("textDetails")
        self.verticalLayout.addWidget(self.textDetails)
        PropriceptionAssessmentWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PropriceptionAssessmentWindow)
        self.statusbar.setObjectName("statusbar")
        PropriceptionAssessmentWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PropriceptionAssessmentWindow)
        QtCore.QMetaObject.connectSlotsByName(PropriceptionAssessmentWindow)

    def retranslateUi(self, PropriceptionAssessmentWindow):
        _translate = QtCore.QCoreApplication.translate
        PropriceptionAssessmentWindow.setWindowTitle(_translate("PropriceptionAssessmentWindow", "Proprioception Assessment Control Window"))
        self.pdStartStopProtocol.setText(_translate("PropriceptionAssessmentWindow", "Start Assessment Protocol"))
        self.checkBoxPauseProtocol.setText(_translate("PropriceptionAssessmentWindow", "Pause Assessment Protocol"))
        self.lblInformation.setText(_translate("PropriceptionAssessmentWindow", "TextLabel"))
