# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/plutoapromassess.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_APRomAssessWindow(object):
    def setupUi(self, APRomAssessWindow):
        APRomAssessWindow.setObjectName("APRomAssessWindow")
        APRomAssessWindow.resize(751, 329)
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        APRomAssessWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(APRomAssessWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 731, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(12)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: rgb(170, 0, 0);")
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.hocGraph = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.hocGraph.setObjectName("hocGraph")
        self.verticalLayout.addWidget(self.hocGraph)
        self.cbTrialRun = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(10)
        self.cbTrialRun.setFont(font)
        self.cbTrialRun.setStyleSheet("color: rgb(170, 0, 0);")
        self.cbTrialRun.setObjectName("cbTrialRun")
        self.verticalLayout.addWidget(self.cbTrialRun)
        self.lblStatus = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setPointSize(10)
        self.lblStatus.setFont(font)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        APRomAssessWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(APRomAssessWindow)
        QtCore.QMetaObject.connectSlotsByName(APRomAssessWindow)

    def retranslateUi(self, APRomAssessWindow):
        _translate = QtCore.QCoreApplication.translate
        APRomAssessWindow.setWindowTitle(_translate("APRomAssessWindow", "PLUTO A/P/AP ROM Assessment"))
        self.lblTitle.setText(_translate("APRomAssessWindow", "PLUTO ROM Assessment"))
        self.cbTrialRun.setText(_translate("APRomAssessWindow", "Trial Run"))
        self.lblStatus.setText(_translate("APRomAssessWindow", "TextLabel"))
