# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/plutopropass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlutoPropAssessor(object):
    def setupUi(self, PlutoPropAssessor):
        PlutoPropAssessor.setObjectName("PlutoPropAssessor")
        PlutoPropAssessor.resize(342, 163)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        PlutoPropAssessor.setFont(font)
        self.centralwidget = QtWidgets.QWidget(PlutoPropAssessor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 122))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbCalibration = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.pbCalibration.setFont(font)
        self.pbCalibration.setObjectName("pbCalibration")
        self.verticalLayout.addWidget(self.pbCalibration)
        self.pbSubject = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.pbSubject.setFont(font)
        self.pbSubject.setObjectName("pbSubject")
        self.verticalLayout.addWidget(self.pbSubject)
        self.pbTestDevice = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.pbTestDevice.setFont(font)
        self.pbTestDevice.setObjectName("pbTestDevice")
        self.verticalLayout.addWidget(self.pbTestDevice)
        self.pbRomAssess = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.pbRomAssess.setFont(font)
        self.pbRomAssess.setObjectName("pbRomAssess")
        self.verticalLayout.addWidget(self.pbRomAssess)
        self.pbPropAssessment = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.pbPropAssessment.setFont(font)
        self.pbPropAssessment.setObjectName("pbPropAssessment")
        self.verticalLayout.addWidget(self.pbPropAssessment)
        PlutoPropAssessor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PlutoPropAssessor)
        self.statusbar.setObjectName("statusbar")
        PlutoPropAssessor.setStatusBar(self.statusbar)

        self.retranslateUi(PlutoPropAssessor)
        QtCore.QMetaObject.connectSlotsByName(PlutoPropAssessor)

    def retranslateUi(self, PlutoPropAssessor):
        _translate = QtCore.QCoreApplication.translate
        PlutoPropAssessor.setWindowTitle(_translate("PlutoPropAssessor", "PLUTO Proprioception Assessment"))
        self.pbCalibration.setText(_translate("PlutoPropAssessor", "Calibrate PLUTO"))
        self.pbSubject.setToolTip(_translate("PlutoPropAssessor", "Select the subject to assess"))
        self.pbSubject.setText(_translate("PlutoPropAssessor", "Select Subject"))
        self.pbTestDevice.setText(_translate("PlutoPropAssessor", "Test Device"))
        self.pbRomAssess.setText(_translate("PlutoPropAssessor", "Assess ROM"))
        self.pbPropAssessment.setText(_translate("PlutoPropAssessor", "Proprioception Assessment"))
