# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plutopropassessment.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTempText = QtWidgets.QLabel(self.centralwidget)
        self.lblTempText.setGeometry(QtCore.QRect(40, 20, 711, 71))
        self.lblTempText.setObjectName("lblTempText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTempText.setText(_translate("MainWindow", "TextLabel"))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    propass = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(propass)
    propass.show()
    sys.exit(app.exec_())