# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/plutoromassess.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RomAssessWindow(object):
    def setupUi(self, RomAssessWindow):
        RomAssessWindow.setObjectName("RomAssessWindow")
        RomAssessWindow.resize(751, 329)
        self.centralwidget = QtWidgets.QWidget(RomAssessWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 731, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.hocGraph = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.hocGraph.setObjectName("hocGraph")
        self.verticalLayout.addWidget(self.hocGraph)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbArom = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.pbArom.setFont(font)
        self.pbArom.setObjectName("pbArom")
        self.horizontalLayout_2.addWidget(self.pbArom)
        self.pbProm = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.pbProm.setFont(font)
        self.pbProm.setObjectName("pbProm")
        self.horizontalLayout_2.addWidget(self.pbProm)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textInstruction = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textInstruction.setEnabled(False)
        self.textInstruction.setMinimumSize(QtCore.QSize(729, 71))
        self.textInstruction.setMaximumSize(QtCore.QSize(729, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.textInstruction.setFont(font)
        self.textInstruction.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(240, 240, 240);")
        self.textInstruction.setObjectName("textInstruction")
        self.verticalLayout.addWidget(self.textInstruction)
        RomAssessWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RomAssessWindow)
        self.statusbar.setObjectName("statusbar")
        RomAssessWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RomAssessWindow)
        QtCore.QMetaObject.connectSlotsByName(RomAssessWindow)

    def retranslateUi(self, RomAssessWindow):
        _translate = QtCore.QCoreApplication.translate
        RomAssessWindow.setWindowTitle(_translate("RomAssessWindow", "PLUTO ROM Assessment"))
        self.label.setText(_translate("RomAssessWindow", "PLUTO ROM Assessment"))
        self.pbArom.setText(_translate("RomAssessWindow", "Assess AROM"))
        self.pbProm.setText(_translate("RomAssessWindow", "Assess PROM"))
