# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/subjectselector.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlutoSubjectSelectorWindow(object):
    def setupUi(self, PlutoSubjectSelectorWindow):
        PlutoSubjectSelectorWindow.setObjectName("PlutoSubjectSelectorWindow")
        PlutoSubjectSelectorWindow.resize(321, 78)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlutoSubjectSelectorWindow.sizePolicy().hasHeightForWidth())
        PlutoSubjectSelectorWindow.setSizePolicy(sizePolicy)
        PlutoSubjectSelectorWindow.setMinimumSize(QtCore.QSize(321, 78))
        PlutoSubjectSelectorWindow.setMaximumSize(QtCore.QSize(321, 78))
        self.centralwidget = QtWidgets.QWidget(PlutoSubjectSelectorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cbSubjID = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.cbSubjID.setFont(font)
        self.cbSubjID.setObjectName("cbSubjID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbSubjID)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.pbSelect = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.pbSelect.setFont(font)
        self.pbSelect.setObjectName("pbSelect")
        self.verticalLayout.addWidget(self.pbSelect)
        PlutoSubjectSelectorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PlutoSubjectSelectorWindow)
        QtCore.QMetaObject.connectSlotsByName(PlutoSubjectSelectorWindow)

    def retranslateUi(self, PlutoSubjectSelectorWindow):
        _translate = QtCore.QCoreApplication.translate
        PlutoSubjectSelectorWindow.setWindowTitle(_translate("PlutoSubjectSelectorWindow", "PLUTO Full Assessment Subject Selector"))
        self.label.setText(_translate("PlutoSubjectSelectorWindow", "Subject ID: "))
        self.pbSelect.setText(_translate("PlutoSubjectSelectorWindow", "Select Subject"))
