# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/subjectselector.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlutoSubjectSelectorWindow(object):
    def setupUi(self, PlutoSubjectSelectorWindow):
        PlutoSubjectSelectorWindow.setObjectName("PlutoSubjectSelectorWindow")
        PlutoSubjectSelectorWindow.resize(450, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlutoSubjectSelectorWindow.sizePolicy().hasHeightForWidth())
        PlutoSubjectSelectorWindow.setSizePolicy(sizePolicy)
        PlutoSubjectSelectorWindow.setMinimumSize(QtCore.QSize(450, 150))
        PlutoSubjectSelectorWindow.setMaximumSize(QtCore.QSize(450, 150))
        self.centralwidget = QtWidgets.QWidget(PlutoSubjectSelectorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setMinimumHeight(30)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cbSubjID = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.cbSubjID.setFont(font)
        self.cbSubjID.setMinimumHeight(30)
        self.cbSubjID.setObjectName("cbSubjID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbSubjID)
        self.verticalLayout.addLayout(self.formLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(10)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.pbSelect = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.pbSelect.setFont(font)
        self.pbSelect.setMinimumHeight(35)
        self.pbSelect.setMinimumWidth(120)
        self.pbSelect.setObjectName("pbSelect")
        self.buttonLayout.addWidget(self.pbSelect)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.buttonLayout)
        PlutoSubjectSelectorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PlutoSubjectSelectorWindow)
        QtCore.QMetaObject.connectSlotsByName(PlutoSubjectSelectorWindow)

    def retranslateUi(self, PlutoSubjectSelectorWindow):
        _translate = QtCore.QCoreApplication.translate
        PlutoSubjectSelectorWindow.setWindowTitle(_translate("PlutoSubjectSelectorWindow", "PLUTO Full Assessment Subject Selector"))
        self.label.setText(_translate("PlutoSubjectSelectorWindow", "Subject ID:"))
        self.pbSelect.setText(_translate("PlutoSubjectSelectorWindow", "Select Subject"))
